# Generated by Django 3.2.16 on 2024-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
                ('emp_starting_time', models.TimeField(choices=[('8:00', '8:00AM'), ('8:30', '8:30AM'), ('9:00', '9:00AM'), ('9:30', '9:30AM')])),
                ('joining_date', models.DateTimeField()),
            ],
        ),
    ]
